# Generated by Django 3.2.18 on 2023-09-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_chefs_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefs',
            name='job_possition',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chefs',
            name='images',
            field=models.ImageField(upload_to='img'),
        ),
    ]
