# Generated by Django 3.2.18 on 2023-09-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_testimonials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chefs',
            new_name='Chef',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='link',
        ),
    ]
