# Generated by Django 3.2.18 on 2023-09-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_personalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='adres',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='openinghours',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
