# Generated by Django 3.2.18 on 2023-09-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20230928_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='openinghours',
            field=models.TextField(max_length=30),
        ),
    ]
